### ISSUE TITLE
Downloadable files

### ISSUE THREAD

**Issue by seimori** [lajcf/ajcf#103]
I need help on this.
I need to implement downloadable files for

- [ ] Press Files
- [ ] Possible downloadable Assets in Articles

**Comment by Nicoowr** [comment]
Dear Issei, how can I help you on this?

**Comment by seimori** [comment]
Dear Nicholas,

as you might remember, we ran into a snag when we tried to make assets downloadable in the PressFiles page.
We left it on the side as we kept our attention on more pressing matters. But now it is necessary for me to visit this problem again, since downloadable assets are also needed for the articles in the Blog.
I have found little help on the interweb to take care of this matter myself. I'm afraid that my global comprehensions of servers and nodejs is seriously lacking. It seemed to me that these were needed to better understand the subject.

Hence, my plea for help.

I await thy reply gratefully
